#%RAML 1.0 NamedExample

  firstName: "Barfour"
  middleName: "Jnr"
  lastName: "Kyei"
  birthDate: "04.11.2020"
  height: "5.11"
  weight: "70kg"
  billingStreet: "Old Town Street"
  billingCity: "ACCRA"
  billingState: "ACCRA"
  billingPostalCode: "233"
  billingCountry: "Ghana"